# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3061e4ee542f4065f60e960b9a19bb851aaa51c8b6f9ab9c94f42e4baae13ef7213f99e09094a8275212163fb0ae7cc8fdb32c734ed8947f34d2a21bb4ad9f24

test:
  secret_key_base: 19ab5500bb5a1ff40d7c6a342250ffc76d8b9b1e232a0d80e0241e8542ee9ad43d5a3f22c7ceb062a6683b0a02ad2372ca848a2c8a9f2199f9010a4cfeb614b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
